# Generated by Django 4.2.1 on 2023-07-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscellaneous_device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miscdevice',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
