# Generated by Django 4.2.1 on 2023-07-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscellaneous_device', '0002_alter_miscdevice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miscdevice',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
