# Generated by Django 4.2.1 on 2023-07-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='status',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
