# Generated by Django 4.2.1 on 2023-07-01 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
