# Generated by Django 4.2.1 on 2023-07-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0002_myuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('employee', 'Employee')], max_length=20),
        ),
    ]
