# Generated by Django 4.2.1 on 2023-07-06 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_remove_location_pincode'),
        ('myuser', '0004_alter_myuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='location.location'),
        ),
    ]
