# Generated by Django 4.2.1 on 2023-07-12 15:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employee', '0001_initial'),
        ('software', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_name', models.CharField(max_length=100)),
                ('asset_id', models.CharField(max_length=6)),
                ('serial_no', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=30)),
                ('make', models.CharField(max_length=20)),
                ('ram', models.CharField(max_length=10)),
                ('hdd', models.CharField(max_length=10)),
                ('catagory', models.CharField(max_length=20)),
                ('operating_system', models.CharField(max_length=20)),
                ('cpu', models.CharField(max_length=10)),
                ('ip_address', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=15)),
                ('buy_date', models.DateField(default=datetime.date.today)),
                ('warranty', models.IntegerField()),
                ('expiry', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Employee.employees')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='location.location')),
                ('softwares', models.ManyToManyField(to='software.software')),
            ],
        ),
    ]
