# Generated by Django 4.2.1 on 2023-07-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_name', models.CharField(max_length=50)),
                ('buy_date', models.DateField()),
                ('price', models.CharField(default=0, max_length=15)),
                ('version', models.CharField(default='NA', max_length=50)),
                ('vendor', models.CharField(default='NA', max_length=50)),
                ('validity', models.CharField(choices=[('yearly', 'Yearly'), ('lifetime', 'Lifetime'), ('monthly', 'Monthly')], default='Lifetime', max_length=50)),
            ],
        ),
    ]
